"use client";

import {Navbar} from "@/components/layout/navbar/Navbar.tsx";
import {useScrollAnimation} from "@/hooks/useScrollAnimation";
import {
    Brain,
    Utensils,
    Dumbbell,
    BarChart3,
} from "lucide-react";

import HeroSection from "@/components/pages/landing/HeroSection.tsx";
import FeaturesSection from "@/components/pages/landing/FeaturesSection";
import HowItWorksSection from "@/components/pages/landing/HowItWorksSection";
import CtaSection from "@/components/pages/landing/CtaSection";
import LandingFooter from "@/components/pages/landing/LandingFooter";

const features = [
    {
        icon: Brain,
        title: "AI-Powered Training",
        description:
            "Get personalized workout plans generated by advanced AI, tailored to your goals and fitness level.",
    },
    {
        icon: Utensils,
        title: "Smart Diet Plans",
        description:
            "Receive customized meal plans that match your nutritional needs and dietary preferences.",
    },
    {
        icon: Dumbbell,
        title: "Workout Notebook",
        description:
            "Track every set, rep, and weight. Log your workouts effortlessly and never miss a detail.",
    },
    {
        icon: BarChart3,
        title: "Progress Analytics",
        description:
            "Visualize your journey with beautiful charts tracking weight, volume, and nutrition.",
    },
];

const benefits = [
    "Personalized programs updated weekly",
    "Track macros and calories automatically",
    "Access from any device",
    "Science-backed training methods",
    "Community support and challenges",
    "Expert-designed exercise library",
];

export default function Landing() {
    const [heroRef, heroVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.1});
    const [featuresRef, featuresVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.1});
    const [howItWorksRef, howItWorksVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.15});
    const [ctaRef, ctaVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.2});

    return (
        <div className="min-h-screen bg-background">
            <Navbar/>

            <HeroSection refEl={heroRef} visible={heroVisible}/>
            <FeaturesSection refEl={featuresRef} visible={featuresVisible} features={features}/>
            <HowItWorksSection refEl={howItWorksRef} visible={howItWorksVisible} benefits={benefits}/>
            <CtaSection refEl={ctaRef} visible={ctaVisible}/>
            <LandingFooter/>
        </div>
    );
}