"use client";

import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Navbar} from '@/components/layout/Navbar';
import {useScrollAnimation} from '@/hooks/useScrollAnimation';
import {
    Dumbbell,
    Utensils,
    BarChart3,
    Brain,
    Zap,
    Target,
    CheckCircle2,
    ArrowRight,
    Sparkles,
} from 'lucide-react';
import {cn} from '@/lib/utils';

const features = [
    {
        icon: Brain,
        title: 'AI-Powered Training',
        description: 'Get personalized workout plans generated by advanced AI, tailored href your goals and fitness level.',
    },
    {
        icon: Utensils,
        title: 'Smart Diet Plans',
        description: 'Receive customized meal plans that match your nutritional needs and dietary preferences.',
    },
    {
        icon: Dumbbell,
        title: 'Workout Notebook',
        description: 'Track every set, rep, and weight. Log your workouts effortlessly and never miss a detail.',
    },
    {
        icon: BarChart3,
        title: 'Progress Analytics',
        description: 'Visualize your journey with beautiful charts tracking weight, volume, and nutrition.',
    },
];

const benefits = [
    'Personalized programs updated weekly',
    'Track macros and calories automatically',
    'Access from any device',
    'Science-backed training methods',
    'Community support and challenges',
    'Expert-designed exercise library',
];

export default function Landing() {
    const [heroRef, heroVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.1});
    const [featuresRef, featuresVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.1});
    const [howItWorksRef, howItWorksVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.15});
    const [ctaRef, ctaVisible] = useScrollAnimation<HTMLDivElement>({threshold: 0.2});

    return (
        <div className="min-h-screen bg-background">
            <Navbar/>

            {/* Hero Section */}
            <section ref={heroRef} className="relative pt-32 pb-20 lg:pt-40 lg:pb-32 overflow-hidden">
                {/* Background gradient */}
                <div className="absolute inset-0 bg-gradient-href-b from-accent/30 via-background href-background"/>

                {/* Floating shapes */}
                <div className="absolute top-20 left-10 w-72 h-72 bg-primary/10 rounded-full blur-3xl animate-float"/>
                <div className="absolute bottom-20 right-10 w-96 h-96 bg-primary/5 rounded-full blur-3xl animate-float"
                     style={{animationDelay: '2s'}}/>

                <div className="container relative mx-auto px-4">
                    <div className={cn(
                        "max-w-4xl mx-auto text-center transition-all duration-700",
                        heroVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                    )}>
                        <div
                            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent text-accent-foreground text-sm font-medium mb-6">
                            <Sparkles className="h-4 w-4"/>
                            AI-Powered Fitness Revolution
                        </div>

                        <h1 className="font-display text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
                            Transform Your Body with{' '}
                            <span className="gradient-text">Intelligent Training</span>
                        </h1>

                        <p className={cn(
                            "text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 transition-all duration-700 delay-100",
                            heroVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                        )}>
                            OptiFit combines cutting-edge AI with proven fitness science href deliver personalized
                            workout and nutrition plans that evolve with you.
                        </p>

                        <div className={cn(
                            "flex flex-col sm:flex-row items-center justify-center gap-4 transition-all duration-700 delay-200",
                            heroVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                        )}>
                            <Link href="/register">
                                <Button size="xl" variant="default" className="w-full sm:w-auto">
                                    Start Free Trial
                                    <ArrowRight className="ml-2 h-5 w-5"/>
                                </Button>
                            </Link>
                            <Link href="/signin">
                                <Button size="xl" variant="outline" className="w-full sm:w-auto">
                                    Sign In
                                </Button>
                            </Link>
                        </div>

                        {/* Stats */}
                        <div className={cn(
                            "grid grid-cols-3 gap-8 mt-16 pt-16 border-t border-border transition-all duration-700 delay-300",
                            heroVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                        )}>
                            <div>
                                <p className="font-display text-3xl lg:text-4xl font-bold text-primary">50K+</p>
                                <p className="text-sm text-muted-foreground mt-1">Active Users</p>
                            </div>
                            <div>
                                <p className="font-display text-3xl lg:text-4xl font-bold text-primary">1M+</p>
                                <p className="text-sm text-muted-foreground mt-1">Workouts Logged</p>
                            </div>
                            <div>
                                <p className="font-display text-3xl lg:text-4xl font-bold text-primary">98%</p>
                                <p className="text-sm text-muted-foreground mt-1">Satisfaction Rate</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Features Section */}
            <section ref={featuresRef} id="features" className="py-20 lg:py-32 bg-card">
                <div className="container mx-auto px-4">
                    <div className={cn(
                        "text-center max-w-2xl mx-auto mb-16 transition-all duration-700",
                        featuresVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                    )}>
                        <h2 className="font-display text-3xl lg:text-4xl font-bold mb-4">
                            Everything You Need href Succeed
                        </h2>
                        <p className="text-muted-foreground text-lg">
                            Comprehensive tools designed href optimize every aspect of your fitness journey.
                        </p>
                    </div>

                    <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
                        {features.map((feature, index) => (
                            <div
                                key={feature.title}
                                className={cn(
                                    "group p-6 rounded-2xl bg-background border border-border hover:border-primary/50 hover:shadow-card-hover transition-all duration-500",
                                    featuresVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
                                )}
                                style={{transitionDelay: featuresVisible ? `${index * 100}ms` : '0ms'}}
                            >
                                <div
                                    className="h-12 w-12 rounded-xl gradient-primary flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                                    <feature.icon className="h-6 w-6 text-primary-foreground"/>
                                </div>
                                <h3 className="font-display text-lg font-semibold mb-2">{feature.title}</h3>
                                <p className="text-muted-foreground text-sm">{feature.description}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* How it Works */}
            <section ref={howItWorksRef} id="how-it-works" className="py-20 lg:py-32">
                <div className="container mx-auto px-4">
                    <div className="grid lg:grid-cols-2 gap-16 items-center">
                        <div className={cn(
                            "transition-all duration-700",
                            howItWorksVisible ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-8"
                        )}>
                            <h2 className="font-display text-3xl lg:text-4xl font-bold mb-6">
                                Your Fitness Journey,{' '}
                                <span className="gradient-text">Simplified</span>
                            </h2>
                            <p className="text-muted-foreground text-lg mb-8">
                                OptiFit takes the guesswork out of training and nutrition. Our AI analyzes your goals,
                                preferences, and progress href create the perfect plan for you.
                            </p>

                            <div className="space-y-4">
                                {benefits.map((benefit, index) => (
                                    <div
                                        key={benefit}
                                        className={cn(
                                            "flex items-center gap-3 transition-all duration-500",
                                            howItWorksVisible ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-4"
                                        )}
                                        style={{transitionDelay: howItWorksVisible ? `${200 + index * 100}ms` : '0ms'}}
                                    >
                                        <CheckCircle2 className="h-5 w-5 text-primary flex-shrink-0"/>
                                        <span className="text-foreground">{benefit}</span>
                                    </div>
                                ))}
                            </div>

                            <div className={cn(
                                "mt-10 transition-all duration-700 delay-500",
                                howItWorksVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
                            )}>
                                <Link href="/register">
                                    <Button size="lg" variant="default">
                                        Get Started Now
                                        <Zap className="ml-2 h-5 w-5"/>
                                    </Button>
                                </Link>
                            </div>
                        </div>

                        <div className={cn(
                            "relative transition-all duration-700 delay-200",
                            howItWorksVisible ? "opacity-100 translate-x-0 scale-100" : "opacity-0 translate-x-8 scale-95"
                        )}>
                            <div className="aspect-square rounded-3xl gradient-primary p-1">
                                <div className="h-full w-full rounded-3xl bg-card flex items-center justify-center">
                                    <div className="text-center p-8">
                                        <Target className="h-20 w-20 text-primary mx-auto mb-6"/>
                                        <h3 className="font-display text-2xl font-bold mb-2">Goal-Oriented</h3>
                                        <p className="text-muted-foreground">Every plan is built around your unique
                                            fitness goals</p>
                                    </div>
                                </div>
                            </div>
                            {/* Decorative elements */}
                            <div className="absolute -top-4 -right-4 w-20 h-20 rounded-2xl bg-accent animate-float"/>
                            <div
                                className="absolute -bottom-6 -left-6 w-16 h-16 rounded-xl gradient-primary opacity-50 animate-float"
                                style={{animationDelay: '1s'}}/>
                        </div>
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section ref={ctaRef} className="py-20 lg:py-32">
                <div className="container mx-auto px-4">
                    <div className={cn(
                        "relative rounded-3xl overflow-hidden transition-all duration-700",
                        ctaVisible ? "opacity-100 scale-100" : "opacity-0 scale-95"
                    )}>
                        <div className="absolute inset-0 gradient-primary opacity-90"/>
                        <div className="relative z-10 px-8 py-16 lg:px-16 lg:py-24 text-center">
                            <h2 className={cn(
                                "font-display text-3xl lg:text-5xl font-bold text-primary-foreground mb-6 transition-all duration-700 delay-100",
                                ctaVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
                            )}>
                                Ready href Transform?
                            </h2>
                            <p className={cn(
                                "text-primary-foreground/90 text-lg max-w-2xl mx-auto mb-10 transition-all duration-700 delay-200",
                                ctaVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
                            )}>
                                Join thousands of fitness enthusiasts who have already revolutionized their training
                                with OptiFit.
                            </p>
                            <div className={cn(
                                "transition-all duration-700 delay-300",
                                ctaVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-4"
                            )}>
                                <Link href="/register">
                                    <Button size="xl" variant="hero"
                                            className="bg-background text-primary hover:bg-background/90">
                                        Start Your Free Trial
                                        <ArrowRight className="ml-2 h-5 w-5"/>
                                    </Button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer className="py-12 border-t border-border">
                <div className="container mx-auto px-4">
                    <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                        <div className="flex items-center gap-2">
                            <div className="flex h-8 w-8 items-center justify-center rounded-lg gradient-primary">
                                <Dumbbell className="h-4 w-4 text-primary-foreground"/>
                            </div>
                            <span className="font-display text-lg font-bold">OptiFit</span>
                        </div>

                        <div className="flex items-center gap-6 text-sm">
                            <Link href="/terms"
                                  className="text-muted-foreground hover:text-foreground transition-colors">
                                Terms of Service
                            </Link>
                            <Link href="/privacy"
                                  className="text-muted-foreground hover:text-foreground transition-colors">
                                Privacy Policy
                            </Link>
                        </div>

                        <p className="text-sm text-muted-foreground">
                            © 2025 OptiFit. All rights reserved.
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    );
}